-- Your SQL goes here

ALTER TABLE categories ADD COLUMN now_u
SMALLINT NOT NULL DEFAULT 1; 
ALTER TABLE items ADD COLUMN now_u
SMALLINT NOT NULL DEFAULT 1;
ALTER TABLE stat_pages ADD COLUMN now_u
SMALLINT NOT NULL DEFAULT 1;
